# action.yml
name: 'API Processor'
description: 'Process Protobuf specification to generate variety endpoints (in Go, JS)'
inputs:
  github_token:
    required: true
    description: "GITHUB_TOKEN. Optional if you use checkout@v2 action."
    default: "${{ github.token }}"
  proto_spec_dir_location:  # id of input
    description: 'The directory with .proto files'
    required: false
    default: 'specs'
  api_dir_location:  # id of input
    description: 'The directory with generated API files'
    required: false
    default: 'api'    
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.proto-spec-dir-location }}
    - ${{ inputs.api-dir-location }}    
branding:
  icon: "circle"
  color: "green"
